version: '3.8'
services:
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=prismadirectusdb
    ports:
      - '5432:5432'
    volumes:
      - ./docker/db:/var/lib/postgresql/data
volumes:
  db:
    driver: local